version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: gbconnectalertas
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: gbconnectalertas
      DATABASE_PASSWORD: gbconnectalertas
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: gbconnectalertas
      POSTGRES_PASSWORD: gbconnectalertas
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
